disable llnl gitlab ci, failing bc adrien is out of quota
LLNL/conduit pull request #737
Opened 2021-03-26 22:32 UTC by cyrush

2021-03-26 22:32 UTC, cyrush commented
@adrienbernede turning this off to hopefully reduce the burden on your fs quotas.

2021-03-29 17:12 UTC, cyrush commented
@adrienbernede  any ideas here? Seems it is now simply failing b/c the CI job running can't become you?

2021-03-29 17:44 UTC, adrienbernede commented
Yup: no runner tag specified, the job may run on any machine, including one I don't have an account on... which is what happened.
For basic scripts, typical tags would be `quartz` and `shell`.

2021-03-29 17:45 UTC, adrienbernede requested changes

2021-03-29 17:45 UTC, adrienbernede commented on .gitlab-ci.yml
> +  stage: build
```suggestion
  stage: build
  tags: [quartz, shell]
```

2021-03-29 18:23 UTC, cyrush commented
@adrienbernede thanks!

2021-03-30 17:13 UTC, merged